# Name shown in GitHub Actions tab
name: Playwright Tests

# When should GitHub run this workflow?
on:

  # Run whenever code is pushed
  push:

  # Also run whenever a Pull Request is created
  pull_request:

jobs:

  # Job name
  test:

    # GitHub creates a fresh Ubuntu machine
    runs-on: ubuntu-latest

    steps:

      # STEP 1
      # Download your GitHub repository
      - name: Checkout Project
        uses: actions/checkout@v4

      # STEP 2
      # Install Node.js
      - name: Setup Node
        uses: actions/setup-node@v4

        with:
          node-version: 22

      # STEP 3
      # Install project dependencies
      - name: Install Packages
        run: npm install

      # STEP 4
      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # STEP 5
      # Run Playwright tests
      - name: Run Tests
        run: npx playwright test
        